###登陆认证，获取token
POST http://{{host}}:{{port}}/sys/authentication/form
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{basic}}

scope=all&grant_type=password&username=admin&password=123456&imageCode=apxw&cid=9c6601a0-1140-40f9-a2a6-a3249d97fc4b

> {%
 client.global.set("token", response.body.access_token);
 %}

###测试
GET http://{{host}}:{{port}}/sys/hello
Accept: application/json
Authorization: bearer {{token}}

###获取登陆用户信息
GET http://{{host}}:{{port}}/sys/me
Accept: application/json
Authorization: bearer {{token}}

###